"use client";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faLandmarkDome,
  faPlus,
  faCameraRetro,
  faArrowPointer,
  faArrowLeft,
  faArrowRight,
  faNewspaper,
  faIdCard,
  faWandMagicSparkles,
  faIdBadge,
  faBan,
  faBolt,
  faBuilding,
  faCalculator,
  faCalendarDays,
  faDice,
  faComment,
  faCircleCheck,
  faChevronRight,
  faXmark,
  faCloudArrowUp,
  faCode,
  faRoute,
  faCrosshairs,
  faGauge,
  faTrash,
  faPeopleGroup,
  faPencil,
  faPenToSquare,
  faNoteSticky,
  faCircleExclamation,
  faChevronUp,
  faChevronDown,
  faTree,
  faListUl,
  faListOl,
  faQuoteLeft,
  faGavel,
  faUsers,
  faUserSlash,
  faHandshake,
  faHourglassEnd,
  faHourglassStart,
  faNetworkWired,
  faImage,
  faBoxArchive,
  faGlobe,
  faFireFlameCurved,
  faLock,
  faRightFromBracket,
  faEnvelope,
  faEnvelopeCircleCheck,
  faBrain,
  faBell,
  faUser,
  faUserPlus,
  faCamera,
  faIndustry,
  faSpinner,
  faMagnifyingGlassChart,
  faRocket,
  faSatelliteDish,
  faClock,
  faGraduationCap,
  faShieldHalved,
  faGaugeHigh,
  faCrosshairs as faSwords,
  faTable,
  faStopwatch,
  faArrowTrendDown,
  faArrowTrendUp,
  faCompass,
  faEye,
  faAward,
  faDiagramProject,
  faChartLine,
  faMicrochip,
  faScaleBalanced,
} from "@fortawesome/free-solid-svg-icons";

const iconMap: Record<string, IconDefinition> = {
  account_balance: faLandmarkDome,
  add: faPlus,
  add_a_photo: faCameraRetro,
  ads_click: faArrowPointer,
  arrow_back: faArrowLeft,
  arrow_forward: faArrowRight,
  article: faNewspaper,
  assignment_ind: faIdCard,
  auto_awesome: faWandMagicSparkles,
  badge: faIdBadge,
  block: faBan,
  bolt: faBolt,
  business: faBuilding,
  calculate: faCalculator,
  calendar_today: faCalendarDays,
  casino: faDice,
  chat: faComment,
  check_circle: faCircleCheck,
  chevron_right: faChevronRight,
  close: faXmark,
  cloud_upload: faCloudArrowUp,
  code: faCode,
  conversion_path: faRoute,
  crisis_alert: faCrosshairs,
  dashboard: faGauge,
  delete: faTrash,
  diversity_1: faPeopleGroup,
  draw: faPencil,
  edit: faPenToSquare,
  edit_note: faNoteSticky,
  error: faCircleExclamation,
  expand_less: faChevronUp,
  expand_more: faChevronDown,
  forest: faTree,
  format_list_bulleted: faListUl,
  format_list_numbered: faListOl,
  format_quote: faQuoteLeft,
  gavel: faGavel,
  group: faUsers,
  group_off: faUserSlash,
  handshake: faHandshake,
  hourglass_empty: faHourglassEnd,
  hourglass_top: faHourglassStart,
  hub: faNetworkWired,
  image: faImage,
  inventory_2: faBoxArchive,
  language: faGlobe,
  local_fire_department: faFireFlameCurved,
  lock: faLock,
  logout: faRightFromBracket,
  mail: faEnvelope,
  mark_email_read: faEnvelopeCircleCheck,
  neurology: faBrain,
  notifications_active: faBell,
  person: faUser,
  person_add: faUserPlus,
  photo_camera: faCamera,
  precision_manufacturing: faMicrochip,
  progress_activity: faSpinner,
  psychology: faBrain,
  query_stats: faMagnifyingGlassChart,
  rocket_launch: faRocket,
  satellite_alt: faSatelliteDish,
  schedule: faClock,
  school: faGraduationCap,
  security: faShieldHalved,
  shield: faShieldHalved,
  speed: faGaugeHigh,
  swords: faScaleBalanced,
  table: faTable,
  timer: faStopwatch,
  trending_down: faArrowTrendDown,
  trending_up: faArrowTrendUp,
  travel_explore: faCompass,
  verified: faCircleCheck,
  visibility: faEye,
  workspace_premium: faAward,
  conversion_path_alt: faDiagramProject,
  trending_up_alt: faChartLine,
};

interface IconProps {
  name: string;
  className?: string;
}

export default function Icon({ name, className = "" }: IconProps) {
  const icon = iconMap[name];
  if (!icon) {
    console.warn(`Icon not found: ${name}`);
    return null;
  }
  return <FontAwesomeIcon icon={icon} className={className} />;
}
